### PR TITLE
Added more options to the fields in the Settings module

### PR DESCRIPTION
**Pull request by SimplyLinn**
I was missing a few "disabled" options, and decided to add it to all fields in the settings module. While I was at it, I also added relevant options to the file picker, which was lacking some options.

### CODE REVIEW

**Comment by rauenzi** [comment]
Some of those changes will not work, they are not HTML input elements and do not work the same way so you can't just `setAttribute` them. Also not all the fields actually support a `disabled` option.

**Comment by SimplyLinn** [comment]
image

**Comment by rauenzi** [comment]
Passive-aggressive comments are not a good way to get your code merged. Yes I did test the code, it did not work on my end. Discord is likely changing their settings objects and is doing a/b testing as their internal code for several of the fields does not yet support a disabled option.

**Comment by SimplyLinn** [comment]
Well, you did claim I just "setAttribute" the setting fields, which I only used on ONE setting field, the FilePicker, which was already a raw HTML element being passed into the SettingField superclass.

**Comment by rauenzi** [comment]
What they A/B test is not really up to me, they do dumb shit internally constantly.

**Comment by rauenzi** [comment]
Forgot about this, `disabled` seems to be working consistently finally. Accepting this.

**Pull request merged**
